@startuml
/'
It is a source file for ATF SAD diagram.
For further information, please, follow http://plantuml.com/
'/

skinparam nodesep 15
!pragma horizontalLineBetweenDifferentPackageAllowed

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

'------------------------------------- '
title ATF - Components Diagram

' ------------ User layer ------------ '
node "User Scripts" as user_layer {
    component "User Script" as Sample
}

' ------------ App layer ------------ '
() "Test" as ITest
package "Application layer" as app_layer {
    component Launch
    component "Connection Test" as Connection

    ' Internal communication
    Connection -up- ITest

    ' Beatifying
    Launch    -[hidden]left- Connection
}

' --------- Business layer ---------- '
() "SDL" as ISDL
() "Test Base" as ITestBase
() "Validator" as IValidator
package "Business layer" as buis_layer {
    component SDL
    component "Test Base" as TestBase
    component Validator

    ' Internal communication
    TestBase  -up- ITestBase
    SDL       -up- ISDL
    Validator -up- IValidator
    TestBase  -up-( ISDL

    ' Beatifying
    ITestBase  -[hidden]left-  ISDL 
    ITestBase  -[hidden]right- IValidator
    TestBase   -[hidden]left-  SDL 
    TestBase   -[hidden]right- Validator
}

' --------- Protocol layer --------- '
() "Protocol Handler"   as IProtocol
() "Mobile Session"     as IMobSession
package "Protocol layer" as ph_layer {
    component "Mobile \n Session"   as MobSession
    component "Protocol \n Handler" as Protocol

    ' Internal communication
    MobSession -up- IMobSession
    Protocol   -up- IProtocol
}

' ------------ TM layer ------------ '
() "HMI Connection"    as IHMIConnection
() "Mobile Connection" as IMobConnection
package "Transport layer" as tm_layer {
	component "HMI Connection" as HMIConnection
    component "Mobile \n Connection" as MobConnection

    ' Internal communication
    MobConnection -up- IMobConnection
    HMIConnection -up- IHMIConnection
}

' ------------ DA layer ------------ '
() "Utils"      as IUtils
() "Config"     as IConfig
() "Events"     as IEvents
() "ATF logger" as IATFLogger
package "Data assess layer" as utils_layer {
    component "Utils"      as Utils
	component "C++ Core"   as CppUtils
	component "ATF logger" as ATFLogger
    component "Events"     as Events
	component "Config"     as Config

    ' Internal communication
    Utils     -up- IUtils
    CppUtils  -up- Utils
    ATFLogger -up- IATFLogger
    Events    -up- IEvents
    Config    -up- IConfig
}
note top of IEvents
    Global interfaces for
    all other components 
end note

' ---- Beatifying layer position ----- '
user_layer  -[hidden]down-  app_layer
utils_layer -[hidden]right- tm_layer
tm_layer    -[hidden]right- ph_layer
ph_layer    -[hidden]right- buis_layer

' ----- Layer connection ------ '
' User to lower layer connections
 Sample -right-( ITest
Launch .up.> Sample : starts \n user script(s)

' App to lower layer connections
Connection --( ISDL
Connection --( ITestBase
Connection --( IValidator
Connection --( IMobSession
Connection --( IMobConnection
Connection --( IHMIConnection
MobConnection -up-( IProtocol

@enduml