@startuml

title ExtensionPendingResumptionHandler


interface EventObserver {
   + on_event(event)
}
 
interface ExtensionPendingResumptionHandler {
  + HandleResumptionSubscriptionRequest()
  + on_event(event)
  + OnResumptionRevert(event)
}

EventObserver <|-down-ExtensionPendingResumptionHandler

class SDLPendingResumptionHandler
class VehicleInfoPendingResumptionHandler
class RCPendingResumptionHandler

SDLPendingResumptionHandler <|-up-ExtensionPendingResumptionHandler
VehicleInfoPendingResumptionHandler <|-up-ExtensionPendingResumptionHandler
RCPendingResumptionHandler <|-up-ExtensionPendingResumptionHandler

class SDLPlugin
SDLPlugin *-right-> SDLPendingResumptionHandler

class VehicleInfoPlugin
VehicleInfoPlugin *-left-> VehicleInfoPendingResumptionHandler

class RCPlugin
RCPlugin *-up-> RCPendingResumptionHandler


@enduml

