@startuml

title ExtensionPendingResumptionHandler


interface EventObserver {
   + on_event(event)
}

interface ResumptionDataProcessor {
  void SubscribeToResponse(const int32_t app_id, const ResumptionRequest& request);
}

interface ExtensionPendingResumptionHandler {
  + HandleResumptionSubscriptionRequest()
  + on_event(event)
  + OnResumptionRevert(event)
}
ExtensionPendingResumptionHandler o-left- ResumptionDataProcessor

EventObserver <|-down-ExtensionPendingResumptionHandler

class SDLPendingResumptionHandler
class VehicleInfoPendingResumptionHandler

SDLPendingResumptionHandler <|-up-ExtensionPendingResumptionHandler
VehicleInfoPendingResumptionHandler <|-up-ExtensionPendingResumptionHandler

class SDLPlugin
SDLPlugin *-right-> SDLPendingResumptionHandler

class VehicleInfoPlugin
VehicleInfoPlugin *-left-> VehicleInfoPendingResumptionHandler

@enduml

