@startuml
/'
It is a source file for SDL SAD sequence diagram.
For further information, please, follow http://plantuml.com/ 
'/

title "Business layer -  RPC processing"
participant "Protocol Handler" as PH #DDDDDD
participant "Application Manager" as AM
participant "Commands" as CS
participant "Request Controller" as RQ
participant "Policy" as P
participant "HMI Message Handler" as HMI #DDDDDD
== Managing Mobile Command ==
PH -> AM : RPC or Bulk data Packet
AM -> AM : Message with JSON, \nbinary and function data
alt Unknown RPC protocol version
    ref over PH, CS: Send UNSUPPORTED_VERSION Mobile Response
    ...
end
alt Parsing or field validation failed
    ref over PH, CS: Send Mobile INVALID_DATA Response
    ...
end
AM -> CS: Run Command
CS -> P : Check RPC and \n application restricts
alt RPC is not allowed by Policy
    ref over PH, CS: Send Mobile DISALLOWED Response
    ...
end
opt
    CS -> CS : Clear parameters \n disallowed by Policies
end
opt HMI communication required
    ref over PH, CS: Send HMI Command
    opt HMI response required
        CS <-] : HMI response result
        ref over PH, CS: Send Mobile Response \n according to HMI result
        ...
    end
end
|||
== Send Mobile Response ==
[o-> AM
AM -> CS: Run Mobile Command
CS -> P : Check fields parameters \nand permissions
alt Target application is registered
    AM -> AM : Convert to JSON
    AM -> PH : RPC/Bulk raw message
end
|||
== Send HMI Command ==
[o-> AM
AM -> CS: Run HMI Command
alt HMI Request
    AM -> RQ : Add to waiting response list
    AM -> HMI : Message
    ...
    alt HMI Response have not received during timeout
        RQ -> CS : Timeout Response
        ref over PH, CS: Send Mobile GENERIC_ERROR Response
        ...
    end
    HMI -> AM: HMI message
    AM -> CS : Pass HMI response result
    ref over PH, CS: Send Mobile Response \n according to HMI result
    ...
end
skinparam defaultFontSize 16
skinparam sequence {
    ArrowColor Blue
    ArrowFontColor #2027E8
    ArrowFontStyle bold
     
    LifeLineBorderColor black
     
    ParticipantBorderColor black
    ParticipantBackgroundColor white
    ParticipantFontSize 17
    ParticipantFontColor black
     
    ActorBorderColor black
    ActorBackgroundColor white
    ActorFontColor Blue
    ActorFontSize 17
    ActorFontName Blue
    DividerBackgroundColor #FEFECE
}
@enduml