@startuml
/'
It is a source file for SDL SAD sequence diagram.
For further information, please, follow http://plantuml.com/ 
'/

title "Business layer - media data transferring"
participant "Protocol Handler" as PH  #DDDDDD
participant "Media Manager" as MM
participant "Application Manager" as AM
participant "Media adapter" as adapter
actor "Pipe" as pipe #DDDDDD
actor "File" as file #DDDDDD
actor "Socket" as socket #DDDDDD
== Media services data recieved from mobile ==
PH -> MM : Media data
MM -> AM : Verify streaming restricts
alt Service is allowed for application
    MM -> adapter : data
    alt Pipe Media Adapter
        adapter -> pipe : data
        ...
        pipe -> adapter : count of written frames
    else File Media Adapter
        adapter -> file : data
        ...
        file -> adapter : count of written frames
    else Socket Media Adapter
        adapter -> socket : data
        ...
        socket -> adapter : count of written frames
    end
    adapter -> MM : Count of written frames
    MM -> PH : Count of written frames
end
skinparam defaultFontSize 16
skinparam sequence {
    ArrowColor Blue
    ArrowFontColor #2027E8
    ArrowFontStyle bold
     
    LifeLineBorderColor black
     
    ParticipantBorderColor black
    ParticipantBackgroundColor white
    ParticipantFontSize 17
    ParticipantFontColor black
     
    ActorBorderColor black
    ActorBackgroundColor white
    ActorFontColor Blue
    ActorFontSize 17
    ActorFontName Blue
    sequenceArrowFontSize  16
    DividerBackgroundColor #FEFECE
}
@enduml