@startuml
/'
It is a source file for SDL SAD sequence diagram.
For further information, please, follow http://plantuml.com/ 
'/

title "Protocol layer - transport notifications processing"
participant "Transport Manager" as TM #DDDDDD
participant "Protocol Handler" as PH
participant "Connection Handler" as CH
participant "Security Manager" as SM
participant "Application Manager" as AM #DDDDDD
participant "Media Manager" as MM #DDDDDD
== Connect, disconnect or error notification ==
alt
    TM -> PH : Notification
else
    TM -> CH : Notification
opt Business layer request
    CH -> AM : Request
    AM -> CH : Response
    CH -> CH : result handling
end
opt Business layer notification
    CH -> AM : Notification
end
skinparam defaultFontSize 16
skinparam sequence {
    ArrowColor Blue
    ArrowFontColor #2027E8
    ArrowFontStyle bold
     
    LifeLineBorderColor black
     
    ParticipantBorderColor black
    ParticipantBackgroundColor white
    ParticipantFontSize 17
    ParticipantFontColor black
     
    ActorBorderColor black
    ActorBackgroundColor white
    ActorFontColor Blue
    ActorFontSize 17
    ActorFontName Blue
    sequenceArrowFontSize  16
 
    DividerBackgroundColor #FEFECE
}
@enduml