@startuml
/'
It is a source file for SDL SAD sequence diagram.
For further information, please, follow http://plantuml.com/ 
'/

title "Transport layer - notification and data transferring"
hide footbox
actor "Device 1" as dev1
actor "Device 2" as dev2
actor "Device 3" as dev3
participant "Transport Adapter 1" as TA1
participant "Transport Adapter 2" as TA2
participant "Transport Manager" as TM
participant "Protocol Handler" as PH  #DDDDDD
== Connect, disconnect, error or data receive notification ==
dev1 -> TA1 : Notification
dev2 -> TA1 : Notification
TA1 -> TM : Device 1 notification
TA1 -> TM : Device 2 notification
dev3 -> TA2 : Notification
TA2 -> TM : Device 3 notification
TM -> PH : Notification with unique device \nor connection identifier
...
== Connect, disconnect or data send required ==
PH -> TM : Control or data message with \n unique device or connection \n identifier
TM -> TA2 : Message for Device 3
TA2 -> dev3 : Notification
 
skinparam defaultFontSize 16
skinparam sequence {
    ArrowColor Blue
    ArrowFontColor #2027E8
    ArrowFontStyle bold
     
    LifeLineBorderColor black
     
    ParticipantBorderColor black
    ParticipantBackgroundColor white
    ParticipantFontSize 17
    ParticipantFontColor black
     
    ActorBorderColor black
    ActorBackgroundColor white
    ActorFontColor Blue
    ActorFontSize 17
    ActorFontName Blue
    DividerBackgroundColor #FEFECE
}
@enduml